microsoft/verisol

- Sources/SolToBoogie/HarnessGenerator.cs
- Test/config/NoConstructor.json
- Test/records.txt
- Test/regressions/NoConstructor.sol
Fix issue #10
-add no constructor handling
-add the corresponding example
> fix constructor

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/ReturnNamedParam.json
- Test/records.txt
- Test/regressions/ReturnNamedParam.sol
> Bug fix for return expr statements

- Sources/SolToBoogie/SourceInfoCollector.cs
This PR fixes the issue "Line breaks confuse the line number generation for trace viewer #39"
The old version didn't handle correctly \r\n newline char, which caused ConcurrencyExplorer to highlight incorrect lines.
> fixing the newline char bug

- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Test/config/Keccak.json
- Test/records.txt
- Test/regressions/Keccak.sol
Addresses #35 when appears non-nested.
> commit for keccak fix when not nested

- Test/regressions/MappingInitialize.sol
- scripts/run_verisol_win.cmd
adding to an existing regression, and minor script change.
> Shuvendu string mapping initialize

- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
Printing Bool values in trace.
> more fixes for printing bool values

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/records.txt
keep track of the current Boogie procedure being translated to
> Fix implicit constructor

- Sources/SolToBoogie/ProcedureTranslator.cs
> print string and bytes values

- Sources/SolToBoogie/BoogieTranslator.cs
- Sources/SolToBoogie/HarnessGenerator.cs
- Sources/SolToBoogie/ModifierCollector.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Sources/SolToBoogie/TranslatorContext.cs
- Test/config/ModifierPost.json
- Test/config/ModifierReturn.json
- Test/records.txt
- Test/regressions/ModifierPost.sol
- Test/regressions/ModifierReturn.sol
multiple modifiers/modifier from inheritance not implemented yet
> Supporting single modifier

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/DeleteScalar.json
- Test/config/StateVarInit.json
- Test/records.txt
- Test/regressions/DeleteArray.sol
- Test/regressions/DeleteScalar.sol
Preliminary support for "delete a[x]" for scalar values and strings.
> Shuvendu delete

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/FuncCallInIfCondition.json
- Test/records.txt
- Test/regressions/FuncCallInIfCondition.sol
1. allowing a function to be used as an if-condition
2. adding one regression test
> added the support for a function to be used as an if-condition (addressing issue #55)

- Sources/SolToBoogie/ModifierCollector.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Sources/SolToBoogieTest/RegressionExecutor.cs
- Test/config/ModifierWithArgs.json
- Test/records.txt
- Test/regressions/ModifierWithArgs.sol
Address #2  
We don't yet handle chaining of multiple modifiers.
> modifier with args and other refactorings

- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/MapArrayHelper.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Test/records.txt
- Test/regressions/NestedArray.sol
- Test/regressions/StructArray.sol
- Test/regressions/StructMemory.sol
- Test/regressions/StructTutorial.sol
- Test/regressions/StructType.sol
- Test/regressions/StructTypeNoTemporaries.sol
- scripts/run_verisol_win.cmd
- scripts/setup_windows.cmd
Support for very preliminary structs (#1)
1. No nested structs
2. struct creation cannot be nested
3. structs cannot be passed to procedures
4. Only by ref semantics supported (storage)
> Shuvendu structs

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/StructNestedConstructor.json
- Test/records.txt
- Test/regressions/StructNestedConstructor.sol
Fix for part of #76 related to nested constructors. 
Fix for #87
> fix for invoking nested constructors

- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Test/regressions/abiEncoded.sol
A partial attempt at fixing nested calls. This will be followed by a major refactoring.
> nested function calls without any relational operations

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/abiLibrary.json
- Test/records.txt
- Test/regressions/Const.sol
- Test/regressions/NestedFunctionCall.sol
- Test/regressions/StructNestedConstructor.sol
- Test/regressions/TypeCast.sol
- Test/regressions/abiEncoded.sol
- Test/regressions/abiLibrary.sol
A cleaner attempt to deal with the nested expressions/function calls (not handling #74 yet), but addressing #73 and #89
> Shuvendu nested expressions

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/NestedArray.json
- Test/records.txt
- Test/regressions/NestedArray.sol
> Shuvendu nested index

- Sources/SolToBoogie/ProcedureTranslator.cs
Address #62 partially. Need to print the line number information.
> printing current contract and function for translationi errors #62

- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TestMain.cs
- Test/regressions/TypeCast.sol
> Shuvendu print context

- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Test/regressions/TypeCast.sol
Address #60 issue and can be closed. Regression typecast.sol extended. 
Almost address #62 for one file. Other files need to be rewritten.
> Shuvendu typecast new

- Sources/SolToBoogie/BoogieTranslator.cs
- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TestMain.cs
- Sources/SolToBoogie/TransUtils.cs
- Sources/SolToBoogie/TranslatorContext.cs
- Sources/SolToBoogieTest/RegressionExecutor.cs
- Test/config/LibraryStruct.json
- Test/records.txt
- Test/regressions/EnumParam.sol
- Test/regressions/LibraryStruct.sol
- scripts/run_verisol_win.cmd
@Yuepeng-Wang  can you look at the changes related to TypeDescriptions vs TypeName?
> Shuvendu library struct

- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/TypeCast.json
- Test/regressions/TypeCast.sol
Addressing #60 and other places where temporaries were not assigned.
> Fixing bugs for tempoaries

- Sources/BoogieAST/BoogieAST.cs
- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogieTest/RegressionExecutor.cs
> adding triggers to multi variable quantifiers

- Sources/VeriSolRunner/VeriSolExecuter.cs
- Sources/VeriSolRunner/VeriSolOutOfBandSpecsRunner.csproj
- Test/regressions/IncDec.sol
For now, only merge the missing csproj file.
> adding mising files

- .gitmodules
- INSTALL.md
- Sources/SolToBoogie/SolToBoogie.csproj
- Sources/SolToBoogieTest/Program.cs
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
- Sources/VeriSolRunner/VeriSolOutOfBandSpecsRunner.csproj
- Sources/VeriSolRunner/VeriSolOutOfBandSpecsRunner.nuspec
1. Adding Corral as a submodule
2. Updating the command line arguments
3. Updating the INSTALL instructions for Windows
> Shuvendu submodules

- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/VeriSolRunner/VeriSolOutOfBandSpecsRunner.nuspec
- Test/regressions/IncDec.sol
- scripts/run_verisol_win.cmd
Address #104 and adjusting nuspec file.
> Shuvendu inc dec

- Sources/VeriSolRunner/Program.cs
- Sources/VeriSolRunner/VeriSolOutOfBandSpecsRunner.nuspec
> updating nuget

- Sources/SolToBoogie/SolToBoogie.csproj
- Sources/SolToBoogieTest/Program.cs
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
- Sources/VeriSolRunner/VeriSolOutOfBandSpecsRunner.csproj
> fixing the issue of copy for linux builds

- Sources/SolToBoogie.sln
- Sources/SolToBoogie/BoogieTranslator.cs
- Sources/SolToBoogie/SolToBoogie.csproj
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
- Sources/VeriSol/Program.cs
- Sources/VeriSol/VeriSol.csproj
- Sources/VeriSol/VeriSolExecuter.cs
- Sources/VeriSolRunner/Program.cs
- Sources/VeriSolRunner/VeriSolExecuter.cs
- Sources/VeriSolRunner/VeriSolOutOfBandSpecsRunner.csproj
* A binary to run VeriSol directly for both proof and counterexample mode
* Tried on test\workbench\AssetTransfer\WrapperFiles and test\workbench\AssetTransfer\FixedVersion
* Change csproj files to copy files to output
> A VeriSol binary

- Sources/SolToBoogie/BoogieTranslator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/VeriSol/Program.cs
- Sources/VeriSol/VeriSolExecuter.cs
- Test/config/ArrayParamCopy.json
- Test/records.txt
- Test/regressions/ArrayParamCopy.sol
- Test/workbench/DefectiveComponentCounter/WrapperFiles/DefectiveComponentCounter.sol
- Test/workbench/FrequentFlyerRewardsCalculator/WrapperFiles/FrequentFlyerRewardsCalculator.sol
- Test/workbench/PingPongGame/WrapperFiles/PingPongGame.sol
- Test/workbench/README.md
- Test/workbench/RoomThermostat/WrapperFiles/RoomThermostat.sol
- Test/workbench/runall.cmd
> Instructions and cleanups to run Workbench

- Libraries/VeriSolContracts.sol
> Verisol library

- Sources/SolToBoogieTest/RegressionExecutor.cs
This fix introduces return values from separate tools invoked during regression execution having different values. This allows to optimize regression output, in particular, to avoid redundant outputs.
> Ellab regression executor fix

- Libraries/ContractInvUsageExample.sol
- Libraries/LoopInvUsageExample.sol
- Libraries/VeriSolContracts.sol
- Sources/BoogieAST/BoogieAST.cs
- Sources/SolToBoogie/BoogieTranslator.cs
- Sources/SolToBoogie/HarnessGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/regressions/LoopWithInv.sol
> Preliminary support for adding loop invariants and contract invariants

- Sources/SolToBoogieTest/Program.cs
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
> Change folder name casing to run regression tests on Linux

- Sources/VeriSol/VeriSolExecuter.cs
First try at #155 
It will probably need improvements after #146 and #157 are done
> Show counterexample trace on console output

- INSTALL.md
- Sources/SolToBoogieTest/Program.cs
- Sources/SolToBoogieTest/RegressionExecutor.cs
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
- Sources/VeriSol/Program.cs
- Sources/VeriSol/VeriSol.csproj
- Sources/VeriSol/VeriSolExecuter.cs
> Shuvendu corral netcore

- Sources/SolToBoogieTest/Program.cs
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
- Sources/VeriSol/Program.cs
- Sources/VeriSol/VeriSol.csproj
- Sources/VeriSol/VeriSolExecuter.cs
Fixing an issue where build has to be performed twice to populate the corral\ folder.
> Ellab csprojfix

- Sources/VeriSol/VeriSolExecuter.cs
- Test/regressions/NamesWithUnderscores_fail.sol
Warning about names with multiple underscores suppressed. 
Test with names with multiple underscores added.
> Ellab nonamewarning

- Binaries/README.md
- INSTALL.md
- README.md
- Sources/SolToBoogie/SolToBoogie.csproj
- Sources/SolToBoogieTest/Program.cs
- Sources/SolToBoogieTest/RegressionExecutor.cs
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
- Sources/VeriSol/Program.cs
- Sources/VeriSol/VeriSol.csproj
- Sources/VeriSolRunner/Program.cs
- azure-pipelines.yml
> Set up CI with Azure Pipelines

- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/HarnessGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/RevertLogicGenerator.cs
- Sources/SolToBoogie/TranslatorContext.cs
- Sources/SolToBoogie/TranslatorFlags.cs
- Sources/SolidityAST/SolidityAST.cs
- Sources/VeriSol/Program.cs
- Initial (and experimental) version of gas instrumentation.
- It extracts gas costs directly from solc. This feature in solc seems to be a bit limited, but it's better than nothing.
- For verisol integration, please use this form of solc: https://github.com/utopia-group/solidity
> Add flag for Gas instrumentation.

- INSTALL.md
Include some details about the need of compiling solc in OSX and the use of brew
> Update install instructions for OSX

- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/MapArrayHelper.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Sources/SolToBoogie/TranslatorContext.cs
- Test/config/UsingForComplex.json
- Test/config/bigintinit.json
- Test/config/block.json
- Test/config/harness.json
- Test/config/tx.json
- Test/records.txt
- Test/regressions/DAO-buggy-call.sol
- Test/regressions/DAO-modular-fixed-call.sol
- Test/regressions/UsingFor.sol
- Test/regressions/UsingForComplex.sol
- Test/regressions/bigintinit.sol
- Test/regressions/harness.sol
- Test/regressions/tx.sol
Issue #71, #189, #192,#88, #193
> A bunch of bug fixes

- Sources/SolToBoogie/BoogieTranslator.cs
- Sources/SolToBoogie/ModSetAnalysis.cs
- Sources/SolToBoogie/TranslatorFlags.cs
- Sources/VeriSol/Program.cs
- Running verisol for with /doModSet now performs modsets for methods.
> Add ModSet Analysis flag.

- INSTALL.md
- Sources/BoogieAST/BoogieAST.cs
- Sources/SolToBoogie/FallbackGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TranslatorFlags.cs
- Sources/VeriSol/Program.cs
- Sources/VeriSol/VeriSolExecuter.cs
- Test/regressions/DAO-modular-fixed-call.sol
- Test/regressions/EnsuresUsageExample.sol
- Test/regressions/Libraries/VeriSolContracts.sol
- Test/regressions/proof_examples.txt
Adds preliminary support for #128  and #203 (for address(x).foo) and fixes to fallback logic.
> more specs

- Sources/SolToBoogie/FallbackGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TranslatorFlags.cs
- Sources/VeriSol/Program.cs
- Sources/VeriSol/VeriSolExecuter.cs
- Test/records.txt
- Test/regressions/DAO-modular-fixed-call.sol
- Test/regressions/EnsuresUsageExample.sol
- Test/regressions/proof_examples.txt
cleaning up command line args
DAO-modular-fixed-call.bpl fixes
> Cleanups of callback logic

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/config/ERC20-modifies.json
- Test/records.txt
- Test/regressions/ERC20-modifies.sol
- Test/regressions/Libraries/VeriSolContracts.sol
> Shuvendu modifies

- README.md
- Sources/SolToBoogie/BoogieTranslator.cs
- Sources/SolToBoogie/HarnessGenerator.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/UsingCollector.cs
- Test/config/FuncsWithUnnamedParams.json
- Test/config/UsingInBase.json
- Test/records.txt
- Test/regressions/FuncsWithUnnamedParams.sol
- Test/regressions/UsingInBase.sol
> Some fixes

- Sources/SolToBoogie/GhostVarAndAxiomGenerator.cs
- Sources/SolToBoogie/HarnessGenerator.cs
- Sources/SolToBoogie/MapArrayHelper.cs
- Sources/SolToBoogie/ParseUtils.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TransUtils.cs
- Sources/SolToBoogie/TranslatorContext.cs
- Sources/SolToBoogie/TranslatorFlags.cs
Some fixes in the gas instrumentation. All the changes are under the "TranslateFlags.InstrumentGas" flag, so none of the default behavior of Verisol is affected.
> Gas Instrumentation

- Sources/SolToBoogie/ProcedureTranslator.cs
- Test/regressions/UintCast.sol
> missing file and check for #247

- Sources/SolToBoogie/HarnessGenerator.cs
- Sources/SolToBoogie/ModifierCollector.cs
- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogie/TranslatorContext.cs
- Test/config/ModifierLocal.json
- Test/records.txt
- Test/regressions/ModifierLocal.sol
> first draft of locals in modifiers #248

- Sources/SolToBoogie/ProcedureTranslator.cs
- Sources/SolToBoogieTest/SolToBoogieTest.csproj
- Test/config/ConstructorChainingUnsoundSmall.json
- Test/records.txt
> making structs distinct at constructor as a hack for #101
